name: Build and Deploy
on:
  push:
    branches:
    - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and deploy
        run: |
          npm ci
          npm run deploy
